import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { APP_VERSION } from '@/lib/app-version';

export interface TabularPdfOptions {
  title: string;
  subtitle?: string;
  reportNumber: string;
  generatedBy: string;
  generatedDate: string;
  generatedTime: string;
  softwareVersion?: string;
  qrDataUrl?: string | null;
  orientation?: 'portrait' | 'landscape';
  columns: string[];
  rows: (string | number)[][];
  summaryLines?: string[];
  placeholders?: string[];
  fileName: string;
}

export function exportTabularPdf(opts: TabularPdfOptions) {
  const doc = new jsPDF({
    orientation: opts.orientation || 'landscape',
    unit: 'pt',
    format: 'a4',
  });

  const marginX = 40;
  let y = 40;

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(opts.title, marginX, y);
  y += 16;

  if (opts.subtitle) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(opts.subtitle, marginX, y);
    y += 14;
  }

  doc.setFontSize(8);
  doc.setTextColor(80);
  const meta = [
    `Report No: ${opts.reportNumber}`,
    `Generated By: ${opts.generatedBy}`,
    `Date: ${opts.generatedDate} ${opts.generatedTime}`,
    `Software: v${opts.softwareVersion || APP_VERSION}`,
  ];
  meta.forEach((line) => {
    doc.text(line, marginX, y);
    y += 11;
  });
  doc.setTextColor(0);

  if (opts.qrDataUrl) {
    try {
      doc.addImage(opts.qrDataUrl, 'PNG', doc.internal.pageSize.getWidth() - 100, 30, 56, 56);
    } catch {
      /* ignore QR render failures */
    }
  }

  if (opts.summaryLines?.length) {
    y += 6;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text('Summary', marginX, y);
    y += 12;
    doc.setFont('helvetica', 'normal');
    opts.summaryLines.forEach((line) => {
      doc.text(line, marginX, y);
      y += 11;
    });
  }

  if (opts.placeholders?.length) {
    y += 4;
    doc.setFontSize(8);
    doc.setTextColor(120);
    opts.placeholders.forEach((line) => {
      doc.text(`Note: ${line}`, marginX, y);
      y += 10;
    });
    doc.setTextColor(0);
  }

  autoTable(doc, {
    startY: y + 8,
    head: [opts.columns],
    body: opts.rows,
    styles: { fontSize: 7, cellPadding: 3 },
    headStyles: { fillColor: [40, 40, 40], textColor: 255 },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    margin: { left: marginX, right: marginX },
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(100);
    doc.text(
      'Controlled Document — For Authorized Use Only',
      marginX,
      doc.internal.pageSize.getHeight() - 20
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.getWidth() - marginX,
      doc.internal.pageSize.getHeight() - 20,
      { align: 'right' }
    );
  }

  doc.save(opts.fileName);
}

export type TabularExporter = (opts: TabularPdfOptions) => void;

/** Extensible registry for future formats (e.g. xlsx). */
export const exportRegistry: Record<string, TabularExporter> = {
  jspdf: exportTabularPdf,
};
