'use client';

import { cn } from '@/lib/utils';
import { ReportQRCode } from './ReportQRCode';

export interface ReportMetadataProps {
  reportTitle: string;
  reportNumber: string;
  generatedBy: string;
  generatedDate: string;
  generatedTime: string;
  softwareVersion: string;
  qrValue?: string;
  className?: string;
}

export function ReportMetadata({
  reportTitle,
  reportNumber,
  generatedBy,
  generatedDate,
  generatedTime,
  softwareVersion,
  qrValue,
  className,
}: ReportMetadataProps) {
  const rows = [
    { label: 'Report Title', value: reportTitle },
    { label: 'Report Number', value: reportNumber },
    { label: 'Generated By', value: generatedBy },
    { label: 'Generated Date', value: generatedDate },
    { label: 'Generated Time', value: generatedTime },
    { label: 'Software Version', value: softwareVersion },
  ];

  return (
    <div
      className={cn(
        'flex flex-wrap items-start justify-between gap-4 rounded-md border border-border bg-muted/20 p-4',
        className
      )}
    >
      <dl className="grid flex-1 grid-cols-1 gap-x-8 gap-y-2 sm:grid-cols-2 lg:grid-cols-3">
        {rows.map((row) => (
          <div key={row.label}>
            <dt className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
              {row.label}
            </dt>
            <dd className="mt-0.5 text-sm text-foreground">{row.value || '—'}</dd>
          </div>
        ))}
      </dl>
      {qrValue && (
        <div className="flex flex-col items-center gap-1">
          <ReportQRCode value={qrValue} size={88} />
          <span className="text-[10px] text-muted-foreground">Verification QR</span>
        </div>
      )}
    </div>
  );
}
