import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
} from '@react-pdf/renderer';
import type { ReactNode } from 'react';

const styles = StyleSheet.create({
  page: {
    paddingTop: 40,
    paddingBottom: 56,
    paddingHorizontal: 40,
    fontSize: 9,
    fontFamily: 'Helvetica',
    color: '#1a1a1a',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
    paddingBottom: 10,
    marginBottom: 12,
  },
  company: { fontSize: 8, color: '#555', marginBottom: 2 },
  title: { fontSize: 14, fontFamily: 'Helvetica-Bold', textAlign: 'right' },
  subtitle: { fontSize: 9, color: '#666', textAlign: 'right', marginTop: 2 },
  metaBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#ddd',
    padding: 8,
    marginBottom: 14,
    backgroundColor: '#fafafa',
  },
  metaCol: { flex: 1, paddingRight: 8 },
  metaLabel: { fontSize: 7, color: '#777', textTransform: 'uppercase', marginBottom: 1 },
  metaValue: { fontSize: 9, marginBottom: 4 },
  qr: { width: 64, height: 64 },
  sectionTitle: {
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    marginTop: 10,
    marginBottom: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: '#bbb',
    paddingBottom: 3,
  },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 0.5,
    borderTopColor: '#ccc',
    paddingTop: 6,
    fontSize: 7,
    color: '#666',
  },
  row: { flexDirection: 'row', marginBottom: 3 },
  label: { width: '35%', color: '#555' },
  value: { width: '65%' },
});

export interface DossierMeta {
  reportTitle: string;
  reportNumber: string;
  generatedBy: string;
  generatedDate: string;
  generatedTime: string;
  softwareVersion: string;
  qrDataUrl?: string | null;
  headerTitle?: string;
  headerSubtitle?: string;
  companyLines?: string[];
  confidentiality?: string;
}

export function DossierKeyValue({
  label,
  value,
}: {
  label: string;
  value?: string | null;
}) {
  return (
    <View style={styles.row}>
      <Text style={styles.label}>{label}</Text>
      <Text style={styles.value}>{value || '—'}</Text>
    </View>
  );
}

export function DossierSection({
  title,
  children,
}: {
  title: string;
  children: ReactNode;
}) {
  return (
    <View wrap={false}>
      <Text style={styles.sectionTitle}>{title}</Text>
      {children}
    </View>
  );
}

export function DossierDocumentShell({
  meta,
  children,
  orientation = 'portrait',
}: {
  meta: DossierMeta;
  children: ReactNode;
  orientation?: 'portrait' | 'landscape';
}) {
  const company = meta.companyLines ?? ['SSDLS', 'Product Lifecycle Management'];
  return (
    <Document>
      <Page size="A4" orientation={orientation} style={styles.page}>
        <View style={styles.header} fixed>
          <View>
            {company.map((line) => (
              <Text key={line} style={styles.company}>
                {line}
              </Text>
            ))}
          </View>
          <View>
            <Text style={styles.title}>{meta.headerTitle || meta.reportTitle}</Text>
            {meta.headerSubtitle && (
              <Text style={styles.subtitle}>{meta.headerSubtitle}</Text>
            )}
          </View>
        </View>

        <View style={styles.metaBox}>
          <View style={styles.metaCol}>
            <Text style={styles.metaLabel}>Report Title</Text>
            <Text style={styles.metaValue}>{meta.reportTitle}</Text>
            <Text style={styles.metaLabel}>Report Number</Text>
            <Text style={styles.metaValue}>{meta.reportNumber}</Text>
            <Text style={styles.metaLabel}>Generated By</Text>
            <Text style={styles.metaValue}>{meta.generatedBy}</Text>
          </View>
          <View style={styles.metaCol}>
            <Text style={styles.metaLabel}>Generated Date</Text>
            <Text style={styles.metaValue}>{meta.generatedDate}</Text>
            <Text style={styles.metaLabel}>Generated Time</Text>
            <Text style={styles.metaValue}>{meta.generatedTime}</Text>
            <Text style={styles.metaLabel}>Software Version</Text>
            <Text style={styles.metaValue}>{meta.softwareVersion}</Text>
          </View>
          {meta.qrDataUrl ? <Image src={meta.qrDataUrl} style={styles.qr} /> : null}
        </View>

        {children}

        <View style={styles.footer} fixed>
          <Text>
            {meta.confidentiality || 'Controlled Document — For Authorized Use Only'}
          </Text>
          <Text
            render={({ pageNumber, totalPages }) =>
              `Page ${pageNumber} of ${totalPages}`
            }
          />
        </View>
      </Page>
    </Document>
  );
}

export const dossierTableStyles = StyleSheet.create({
  table: { marginBottom: 8 },
  headerRow: {
    flexDirection: 'row',
    backgroundColor: '#eee',
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
    paddingVertical: 3,
    paddingHorizontal: 2,
  },
  row: {
    flexDirection: 'row',
    borderBottomWidth: 0.5,
    borderBottomColor: '#ddd',
    paddingVertical: 2,
    paddingHorizontal: 2,
  },
  cell: { fontSize: 7, paddingRight: 2 },
  headerCell: { fontSize: 7, fontFamily: 'Helvetica-Bold', paddingRight: 2 },
});
